baseURL = "https://johnsinco.github.io/"
languageCode = "en-us"
title = "John Stewart - Software Development and Consulting"

theme = "coder" # set the theme

[params] # theme parameters
    author = "John Stewart" # author's name
    info = "John Stewart is a Software Engineer and Leader with 15 years experience delivering results for organizations and clients." # author's job title or info
    description = "John Stewart - Evergreen Colorado - Software Development and Consulting" # site description
    keywords = "blog,developer,personal,consulting,for-hire" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/johnsinco/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/john_s_in_co/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/johnmstewart/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
